#!/bin/bash

#leer nombres de archivos fastq
for i in $(ls *.fastq); do
  noex="${i%.*}" #archivo sin extension
  # contar lineas de archivo fastq, obtener solo el numero de lineas e imprimir
  #num_read=$(wc -l $i| awk '{print $2,"tiene",$1/4,"reads"}')
  num_read=$(wc -l $i| awk '{print $1/4}')
  
  read_info=$(vdb-dump --info $noex| grep "SEQ"| awk '{print $3}'|sed 's/,//g')
  
  if [ "$numread" == "$readinfo"]; then 
    echo "$noex tiene $num_read reads y esta .... OK"
  else
    echo "$noex tiene $num_read reads y deberia tener $read_info reads .... Descarga fallida"
  fi
  #echo $num_read 
done



#vdb-dump --info SRR11305406|grep "SEQ" 
